### ISSUE TITLE
Impossible to access an attribute ("avatar") on a string variable ("anon.").

### ISSUE THREAD

**Issue by tofra** [avanzu/AdminThemeBundle#147]
When implementing the ShowUserListener, and not logged in, then this error is shown. When you have logged in, the error doesn't occur.

**Comment by lucasaba** [comment]
Can you show your ShowUserListener implementation (and service configuration) ? 
And, did you override the base-layout ?

That error shouldn't happen since the user navbar should be called only if the user is fully authnticated (https://github.com/avanzu/AdminThemeBundle/blob/master/Resources/views/layout/base-layout.html.twig#L50).

**Comment by shakaran** [comment]
@tofra is still this an issue? Do you resolve it or is present?

**Comment by tofra** [comment]
I can't see anymore where it exactly did go wrong (and I didn't mentioned it in the ticket :-( )
So let's close it for know, as code wise it looks good..

**Comment by shakaran** [comment]
@tofra Thanks, don't hesitate in reopen the ticket if you observe the problem again.
