### ISSUE TITLE
Is the project still active ? Can I give an hand ?

### ISSUE THREAD

**Issue by lucasaba** [avanzu/AdminThemeBundle#156]
It seems that the last operation on this project had been 3 months ago.
Is it still actively developed ?
Do you need some help ? I'd be glad to help!

**Comment by chteuchteu** [comment]
It's not as active as it was, but is still maintained. @avanzu is in charge of the releases, and some of us are in PR review duty.
Don't hesitate to contribute by answering to issues and creating pull requests, your help will be appreciated !
I'm closing this issue since I answered your question, but don't hesitate to ask any question you have in mind here
