### ISSUE TITLE
Login page jquery version is incorrect

### ISSUE THREAD

**Issue by pabloveintimilla** [avanzu/AdminThemeBundle#190]
When you update jquery (ex to 2.2.3), the link breaks.

https://github.com/avanzu/AdminThemeBundle/blob/75a7b44365796671e492f82463179486a9e13e09/Resources/views/layout/login-layout.html.twig#L102

**Comment by shakaran** [comment]
@pabloveintimilla could you specify more which kind of error receive? which error shows In javascript console?
Also it seems that you don't fill the Symfony version and AdminThemeBundle, could you specify in which version are you using?

**Comment by pabloveintimilla** [comment]
@shakaran the error is 404 file not found. Because jquery version after update is 2.2.3.  The url of jquery should be dynamic. My symfony version is 3.3 and the AdminThemeBundle is the current master-dev.

**Comment by shakaran** [comment]
I understand now. I push a fix for this in master. Unfortunally, the jquery version cames prefixed from upstream AdminLTE, so if you don't mind, you could open a issue in [almasaeed2010/AdminLTE](almasaeed2010/AdminLTE) requesting that change. AdminThemeBundle is picking that file from vendor/almasaeed2010/adminlte/plugins/jQuery/jQuery-2.2.0.min.js, so you should request that they modify to vendor/almasaeed2010/adminlte/plugins/jQuery/jQuery.min.js or provide the two ways (one linked to the version and unversioned). Closing this issue since is fixed now in master. Thanks for your reporting and make better this bundle!
