### ISSUE TITLE
Additional attributes on Menu item Missing feature

### ISSUE THREAD

**Issue by aftabnaveed** [avanzu/AdminThemeBundle#59]
It seems like you can't add additional attributes like on onclick a menu item, is that something which is easy to achieve. I actually have an idea of implementing it, and would be happy to contribute that to the bundle. 

This issue is somewhat related to #58  which I created before.

**Comment by avanzu** [comment]
This should be doable, i guess. 

You will need to: 
- create your own MenuItem Class which implements the MenuItemInterface (or simply extend the existing MenuItemModel) in order to hold the additional attributes. 
- Use your custom menu items for the corresponding events (e.g. SidebarMenuEvent)
- Either override the ``menu_item`` macro in  ``AvanzuAdminThemeBundle:layout:macros.html.twig`` to actually use the attributes provided by the custom menu item class. 
- Or override the ``AvanzuAdminThemeBundle:Sidebar:menu.html.twig`` and build the menu differently.

**Comment by aftabnaveed** [comment]
Thanks @avanzu  for the feedback and such a wonderful Bundle, I did it exactly the same way in my MenuItemModel and added an extra property attributes and relevant getters & setters. I also overrode the macros.html.twig in my custom Bundle, but I thought there would be a simpler way of doing that.

Now I have to copy over entire macros.html.twig whenever it gets updated in future, and that's why I was avoiding to override it, but I appreciate your answer.

**Comment by hounded** [comment]
did this ever get done i'm getting the following message in my unit tests 
```console

Calling "attributes" on template "AvanzuAdminThemeBundle:Partials:_menu.html.twig" from template "AvanzuAdminThemeBundle:Partials:_menu.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0: 8x
    8x in DefaultControllerTest::testLogin from Tests\AppBundle\Controller
```

**Comment by hounded** [comment]
Submitted pull https://github.com/avanzu/AdminThemeBundle/pull/152 request to fix 
`Calling "attributes" on template "AvanzuAdminThemeBundle:Partials:_menu.html.twig" from template "AvanzuAdminThemeBundle:Partials:_menu.html.twig" is deprecated since version 1.28 and won't be supported anymore in 2.0`

As detailed in https://github.com/KnpLabs/KnpMenu/issues/250

**Comment by shakaran** [comment]
@hounded closing this issue since #152 has been merged
